# Compose for local dev
services:
  db:
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3301:3306"
    networks:
      auto_net:
  app:
    image: maven:3.9.9-eclipse-temurin-21-alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: mvn spring-boot:run
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8081:8080"
    networks:
      auto_net:
networks:
  auto_net:
