FROM eclipse-temurin:21-jdk-alpine
EXPOSE 8080

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

WORKDIR /app
RUN mkdir -p /app/upload-dir

ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}

ENTRYPOINT ["java","-jar","/app.jar"]